spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trvl?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rhdwnsla1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    multipart:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log.impl: org.apache.ibatis.logging.stdout.StdOutImpl

open:
  api:
    url: "http://apis.data.go.kr"
    accident-list: "/1262000/AccidentService/getAccidentList"
