spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trvl?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: rhdwnsla1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    multipart:
      enabled: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log.impl: org.apache.ibatis.logging.stdout.StdOutImpl

open:
  api:
    url: "http://apis.data.go.kr"
    regulation: "http://apis.data.go.kr/1262000/EntranceVisaService2/getEntranceVisaList2"
    standardCode: "http://apis.data.go.kr/1262000/CountryCodeService2/getCountryCodeList2"
    countryFlag: "http://apis.data.go.kr/1262000/CountryFlagService2/getCountryFlagList2"
    countryInfo: "http://apis.data.go.kr/1262000/CountryGnrlInfoService2/getCountryGnrlInfoList2"
    notice: "http://apis.data.go.kr/1262000/NoticeService2/getNoticeList2"
    safetyList: "http://apis.data.go.kr/1262000/CountrySafetyService3/getCountrySafetyList3"
    covidSafety: "http://apis.data.go.kr/1262000/CountryCovid19SafetyServiceNew/getCountrySafetyNewsListNew"
    overSeasArrival: "http://apis.data.go.kr/1262000/CountryOverseasArrivalsService/getCountryOverseasArrivalsList"
    embassyInfo: "http://apis.data.go.kr/1262000/EmbassyService2/getEmbassyList2"
    embassyHomepage: "http://apis.data.go.kr/1262000/EmbassyHomepageService2/getEmbassyHomepageList2"
    contactPoint: "http://apis.data.go.kr/1262000/LocalContactService2/getLocalContactList2"
    travelAlarm: "http://apis.data.go.kr/1262000/TravelAlarmService2/getTravelAlarmList2"
    accidentList: "/1262000/AccidentService/getAccidentList"
    countryBasicInfo: "/1262000/CountryBasicService/getCountryBasicList"
    timeout: 300
