package com.tistory.amyyzzin.trvl.constant;

import com.tistory.amyyzzin.trvl.domain.StandardCode;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class IsoConstant {

        private static StandardCode standardCode;

    static final Map<String, String> COUNTRY_ISOALP2_MAP =
        Collections.unmodifiableMap(new HashMap<>() {{
            put("Ghana", "GH");
            put("Gabon", "GA");
            put("Guyana", "GY");
            put("Gambia", "GM");
            put("Guatemala", "GT");
            put("Grenada", "GD");
            put("Greece", "GR");
            put("Guinea", "GN");
            put("Guinea-Bissau", "GW");
            put("Namibia", "NA");
            put("Nauru", "NR");
            put("Nigeria", "NG");
            put("Republic of South Sudan", "SS");
            put("Republic of South Africa", "ZA");
            put("Netherlands", "NL");
            put("Nepal", "NP");
            put("Norway", "NO");
            put("New Zealand", "NZ");
            put("Niue", "NU");
            put("Niger", "NE");
            put("Nicaragua", "NI");
            put("Taiwan", "TW");
            put("Denmark", "DK");
            put("Dominican Republic", "DO");
            put("Dominica", "DM");
            put("Germany", "DE");
            put("East Timor", "TL");
            put("Laos", "LA");
            put("Liberia", "LR");
            put("Latvia", "LV");
            put("Russia", "RU");
            put("Lebanon", "LB");
            put("Lesotho", "LS");
            put("Romania", "RO");
            put("Luxembourg", "LU");
            put("Rwanda", "RW");
            put("Libya", "LY");
            put("Lithuania", "LT");
            put("Liechtenstein", "LI");
            put("Madagascar", "MG");
            put("Marshall Islands", "MH");
            put("Micronesia", "FM");
            put("Macau", "MO");
            put("Malawi", "MW");
            put("Malaysia", "MY");
            put("Mali", "ML");
            put("Mexico", "MX");
            put("Monaco", "MC");
            put("Morocco", "MA");
            put("Mauritius", "MU");
            put("Mauritania", "MR");
            put("Mozambique", "MZ");
            put("Montenegro", "ME");
            put("Moldova", "MD");
            put("Maldives", "MV");
            put("Malta", "MT");
            put("Mongolia", "MN");
            put("United States of America", "US");
            put("Myanmar", "MM");
            put("Vanuatu", "VU");
            put("Bahrain", "BH");
            put("Barbados", "BB");
            put("Bahamas", "BS");
            put("Bangladesh", "BD");
            put("Benin", "BJ");
            put("Venezuela", "VE");
            put("Vietnam", "VN");
            put("Belgium", "BE");
            put("Belarus", "BY");
            put("Belize", "BZ");
            put("Bosnia and Herzegovina", "BA");
            put("Botswana", "BW");
            put("Bolivia", "BO");
            put("Burundi", "BI");
            put("Burkina Faso", "BF");
            put("Bhutan", "BT");
            put("North Macedonia", "MK");
            put("Bulgaria", "BG");
            put("Brazil", "BR");
            put("Brunei", "BN");
            put("Samoa", "WS");
            put("Saudi Arabia", "SA");
            put("Cyprus", "CY");
            put("San Marino", "SM");
            put("Sao Tome and Principe", "ST");
            put("Senegal", "SN");
            put("Serbia", "RS");
            put("Saint Lucia", "LC");
            put("St. Vincent and the Grenadines", "VC");
            put("Saint Kitts and Nevis", "KN");
            put("Somalia", "SO");
            put("Solomon lslands", "SB");
            put("Sudan", "SD");
            put("Suriname", "SR");
            put("Sri Lanka", "LK");
            put("Sweden", "SE");
            put("Switzerland", "CH");
            put("Spain", "ES");
            put("Slovakia", "SK");
            put("Slovenia", "SI");
            put("Syria", "SY");
            put("Sierra Leone", "SL");
            put("Singapore", "SG");
            put("United Arab Emirates", "AE");
            put("Armenia", "AM");
            put("Argentina", "AR");
            put("Iceland", "IS");
            put("Haiti", "HT");
            put("Ireland", "IE");
            put("Azerbaijan", "AZ");
            put("Afghanistan", "AF");
            put("Andorra", "AD");
            put("Albania", "AL");
            put("Algeria", "DZ");
            put("Angola", "AO");
            put("Antigua and Barbuda", "AG");
            put("Eritrea", "ER");
            put("Kingdom of Eswatini", "SZ");
            put("Estonia", "EE");
            put("Ecuador", "EC");
            put("Ethiopia", "ET");
            put("El Salvador", "SV");
            put("United Kingdom", "GB");
            put("Yemen", "YE");
            put("Oman", "OM");
            put("Austria", "AT");
            put("Honduras", "HN");
            put("Jordan", "JO");
            put("Uganda", "UG");
            put("Uruguay", "UY");
            put("Uzbekistan", "UZ");
            put("Ukraine", "UA");
            put("Iraq", "IQ");
            put("Iran", "IR");
            put("Israel", "IL");
            put("Egypt", "EG");
            put("Italy", "IT");
            put("India", "IN");
            put("Indonesia", "ID");
            put("Japan", "JP");
            put("Jamaica", "JM");
            put("Zambia", "ZM");
            put("Equatorial Guinea", "GQ");
            put("Georgia", "GE");
            put("China", "CN");
            put("Central African Republic", "CF");
            put("Djibouti", "DJ");
            put("Zimbabwe", "ZW");
            put("Chad", "TD");
            put("Czech Republic", "CZ");
            put("Chile", "CL");
            put("Cameroon", "CM");
            put("CapeVerde", "CV");
            put("Kazakhstan", "KZ");
            put("Qatar", "QA");
            put("Cambodia", "KH");
            put("Canada", "CA");
            put("Kenya", "KE");
            put("Kosovo", "XK");
            put("CostaRica", "CR");
            put("Cote d Ivoire", "CI");
            put("Colombia", "CO");
            put("Republic of Congo", "CG");
            put("Democratic Republic of the Congo", "CD");
            put("Cuba", "CU");
            put("Kuwait", "KW");
            put("Cook Island", "CK");
            put("Croatia", "HR");
            put("Kyrgyzstan", "KG");
            put("Kiribati", "KI");
            put("Tajikistan", "TJ");
            put("Tanzania", "TZ");
            put("Thailand", "TH");
            put("Togo", "TG");
            put("Tonga", "TO");
            put("Turkmenistan", "TM");
            put("tuvalu", "TV");
            put("Tunisia", "TN");
            put("Türkiye", "TR");
            put("Trinidad and Tobago", "TT");
            put("Panama", "PA");
            put("Paraguay", "PY");
            put("Pakistan", "PK");
            put("Papua New Guinea", "PG");
            put("Palau", "PW");
            put("Peru", "PE");
            put("Portugal", "PT");
            put("Poland", "PL");
            put("France", "FR");
            put("Fiji", "FJ");
            put("Finland", "FI");
            put("Philippines", "PH");
            put("Hungary", "HU");
            put("Australia", "AU");
            put("hongkong", "HK");
            put("Seychelles", "SC");
            put("Comoros", "KM");
        }});

    public static String convertCountryEngNm2Iso2(String countryEngNm) {
        int len = countryEngNm.length();
        countryEngNm = countryEngNm.charAt(len - 1) == ' ' ?
                countryEngNm.substring(0, len - 1) : countryEngNm;

        if (COUNTRY_ISOALP2_MAP.containsKey(countryEngNm)) {
            return COUNTRY_ISOALP2_MAP.get(countryEngNm);
        }

        return "";
    }
}
