package com.tistory.amyyzzin.trvl.constant;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class IsoConstant {

    static final Map<String, String> COUNTRY_ISOALP3_MAP =
        Collections.unmodifiableMap(new HashMap<>() {{
            put("Ghana", "GHA");
            put("Gabon", "GAB");
            put("Guyana", "GUY");
            put("Gambia", "GMB");
            put("Guatemala", "GTM");
            put("Grenada", "GRD");
            put("Greece", "GRC");
            put("Guinea", "GIN");
            put("Guinea-Bissau", "GNB");
            put("Namibia", "NAM");
            put("Nauru", "NRU");
            put("Nigeria", "NGA");
            put("Republic of South Sudan", "SSD");
            put("Republic of South Africa", "ZAF");
            put("Netherlands", "NLD");
            put("Nepal", "NPL");
            put("Norway", "NOR");
            put("New Zealand", "NZL");
            put("Niue", "NIU");
            put("Niger", "NER");
            put("Nicaragua", "NIC");
            put("Taiwan", "TWN");
            put("Denmark", "DNK");
            put("Dominican Republic", "DOM");
            put("Dominica", "DMA");
            put("Germany", "DEU");
            put("East Timor", "TLS");
            put("Laos", "LAO");
            put("Liberia", "LBR");
            put("Latvia", "LVA");
            put("Russia", "RUS");
            put("Lebanon", "LBN");
            put("Lesotho", "LSO");
            put("Romania", "ROU");
            put("Luxembourg", "LUX");
            put("Rwanda", "RWA");
            put("Libya", "LBY");
            put("Lithuania", "LTU");
            put("Liechtenstein", "LIE");
            put("Madagascar", "MDG");
            put("Marshall Islands", "MHL");
            put("Micronesia", "FSM");
            put("Macau", "MAC");
            put("Malawi", "MWI");
            put("Malaysia", "MYS");
            put("Mali", "MLI");
            put("Mexico", "MEX");
            put("Monaco", "MCO");
            put("Morocco", "MAR");
            put("Mauritius", "MUS");
            put("Mauritania", "MRT");
            put("Mozambique", "MOZ");
            put("Montenegro", "MNE");
            put("Moldova", "MDA");
            put("Maldives", "MDV");
            put("Malta", "MLT");
            put("Mongolia", "MNG");
            put("United States of America", "USA");
            put("Myanmar", "MMR");
            put("Vanuatu", "VUT");
            put("Bahrain", "BHR");
            put("Barbados", "BRB");
            put("Bahamas", "BHS");
            put("Bangladesh", "BGD");
            put("Benin", "BEN");
            put("Venezuela", "VEN");
            put("Vietnam", "VNM");
            put("Belgium", "BEL");
            put("Belarus", "BLR");
            put("Belize", "BLZ");
            put("Bosnia and Herzegovina", "BIH");
            put("Botswana", "BWA");
            put("Bolivia", "BOL");
            put("Burundi", "BDI");
            put("Burkina Faso", "BFA");
            put("Bhutan", "BTN");
            put("North Macedonia", "MKD");
            put("Bulgaria", "BGR");
            put("Brazil", "BRA");
            put("Brunei", "BRN");
            put("Samoa", "WSM");
            put("Saudi Arabia", "SAU");
            put("Cyprus", "CYP");
            put("San Marino", "SMR");
            put("Sao Tome and Principe", "STP");
            put("Senegal", "SEN");
            put("Serbia", "SRB");
            put("Saint Lucia", "LCA");
            put("St. Vincent and the Grenadines", "VCT");
            put("Saint Kitts and Nevis", "KNA");
            put("Somalia", "SOM");
            put("Solomon lslands", "SLB");
            put("Sudan", "SDN");
            put("Suriname", "SUR");
            put("Sri Lanka", "LKA");
            put("Sweden", "SWE");
            put("Switzerland", "CHE");
            put("Spain", "ESP");
            put("Slovakia", "SVK");
            put("Slovenia", "SVN");
            put("Syria", "SYR");
            put("Sierra Leone", "SLE");
            put("Singapore", "SGP");
            put("United Arab Emirates", "ARE");
            put("Armenia", "ARM");
            put("Argentina", "ARG");
            put("Iceland", "ISL");
            put("Haiti", "HTI");
            put("Ireland", "IRL");
            put("Azerbaijan", "AZE");
            put("Afghanistan", "AFG");
            put("Andorra", "AND");
            put("Albania", "ALB");
            put("Algeria", "DZA");
            put("Angola", "AGO");
            put("Antigua and Barbuda", "ATG");
            put("Eritrea", "ERI");
            put("Kingdom of Eswatini", "SWZ");
            put("Estonia", "EST");
            put("Ecuador", "ECU");
            put("Ethiopia", "ETH");
            put("El Salvador", "SLV");
            put("United Kingdom", "GBR");
            put("Yemen", "YEM");
            put("Oman", "OMN");
            put("Austria", "AUT");
            put("Honduras", "HND");
            put("Jordan", "JOR");
            put("Uganda", "UGA");
            put("Uruguay", "URY");
            put("Uzbekistan", "UZB");
            put("Ukraine", "UKR");
            put("Iraq", "IRQ");
            put("Iran", "IRN");
            put("Israel", "ISR");
            put("Egypt", "EGY");
            put("Italy", "ITA");
            put("India", "IND");
            put("Indonesia", "IDN");
            put("Japan", "JPN");
            put("Jamaica", "JAM");
            put("Zambia", "ZMB");
            put("Equatorial Guinea", "GNQ");
            put("Georgia", "GEO");
            put("China", "CHN");
            put("Central African Republic", "CAF");
            put("Djibouti", "DJI");
            put("Zimbabwe", "ZWE");
            put("Chad", "TCD");
            put("Czech Republic", "CZE");
            put("Chile", "CHL");
            put("Cameroon", "CMR");
            put("CapeVerde", "CPV");
            put("Kazakhstan", "KAZ");
            put("Qatar", "QAT");
            put("Cambodia", "KHM");
            put("Canada", "CAN");
            put("Kenya", "KEN");
            put("Kosovo", "XKX");
            put("CostaRica", "CRI");
            put("Cote d Ivoire", "CIV");
            put("Colombia", "COL");
            put("Republic of Congo", "COG");
            put("Democratic Republic of the Congo", "COD");
            put("Cuba", "CUB");
            put("Kuwait", "KWT");
            put("Cook Island", "COK");
            put("Croatia", "HRV");
            put("Kyrgyzstan", "KGZ");
            put("Kiribati", "KIR");
            put("Tajikistan", "TJK");
            put("Tanzania", "TZA");
            put("Thailand", "THA");
            put("Togo", "TGO");
            put("Tonga", "TON");
            put("Turkmenistan", "TKM");
            put("tuvalu", "TUV");
            put("Tunisia", "TUN");
            put("Türkiye", "TUR");
            put("Trinidad and Tobago", "TTO");
            put("Panama", "PAN");
            put("Paraguay", "PRY");
            put("Pakistan", "PAK");
            put("Papua New Guinea", "PNG");
            put("Palau", "PLW");
            put("Peru", "PER");
            put("Portugal", "PRT");
            put("Poland", "POL");
            put("France", "FRA");
            put("Fiji", "FJI");
            put("Finland", "FIN");
            put("Philippines", "PHL");
            put("Hungary", "HUN");
            put("Australia", "AUS");
            put("hongkong", "HKG");
            put("Seychelles", "SYC");
            put("Comoros", "COM");
        }});

    public static String convertCountryEngNm2Iso3(String countryEngNm) {
        int len = countryEngNm.length();
        countryEngNm = countryEngNm.charAt(len - 1) == ' ' ?
                countryEngNm.substring(0, len - 1) : countryEngNm;

        if (COUNTRY_ISOALP3_MAP.containsKey(countryEngNm)) {
            return COUNTRY_ISOALP3_MAP.get(countryEngNm);
        }

        return "";
    }
}
